version: "3.9"
services:
  deep-lynx:
    image: "idaholab/deeplynx:latest"
    restart: on-failure
    depends_on:
      - timescaledb
      - rabbitmq
    ports:
      - "8090:8090"
    env_file:
      - "./.docker-env"
  redis-load:
    build: ./RedisLoader
    restart: on-failure
    depends_on:
      - deep-lynx
      - timescaledb
      - redis
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:root@timescaledb/deep_lynx_dev
      - REDIS_CONNECTION_STRING=redis://redis:6379
      - WAIT_HOSTS=deep-lynx:8090
  timescaledb:
    environment:
      - POSTGRES_PASSWORD=root
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - "5432:5432"
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=deeplynx
      - RABBITMQ_DEFAULT_PASS=root
    image: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
